### ISSUE TITLE
ip 无法访问了

### ISSUE THREAD

**Issue by cmmei** [LirenCollege/LirenCollegeBBS#1]
123.56.10.32:8000 无法访问了

**Comment by tsai1993** [comment]
囧……我现在连服务器都 ssh 不上，除了提交工单，别无办法。

**Comment by tsai1993** [comment]
可以连上了，不过改为 80 端口了，直接访问 123.56.10.32 。

再观察一段时间，看看是否是数据库的问题。

**Comment by tsai1993** [comment]
目前已经排除是本站引起的内存满载，是我那台服务器上其他服务的原因。并且站长已经表明也不是数据库的问题，https://www.youbbs.org/t/2164 。
