### ISSUE TITLE
选择分类不能覆盖所有选项

### ISSUE THREAD

**Issue by tsai1993** [LirenCollege/LirenCollegeBBS#10]
发帖或者管理员移动帖子时无法选择所有分类选项

**Comment by tsai1993** [comment]
修改 `config.yaml` 里的 `MainNodeIds: "1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20"`

可以解决此问题。

**Comment by cmmei** [comment]
OK 了。
