### ISSUE TITLE
建议修改几个参数

### ISSUE THREAD

**Issue by tsai1993** [LirenCollege/LirenCollegeBBS#11]
https://github.com/LirenCollege/LirenCollegeBBS/blob/284e0a4229a4022de354bf3aeec4125f4f192083/config/config.yaml#L21

建议修改几个参数，一是首页帖子数量，建议在30个以上；二是帖子回复显示数量，现在只有十个，翻页太烦，建议在50。其他的标签显示数量看着加吧

**Comment by cmmei** [comment]
已改。
