### ISSUE TITLE
主页添加简单介绍

### ISSUE THREAD

**Issue by tsai1993** [LirenCollege/LirenCollegeBBS#13]
感觉缺少一个突出特色的介绍，简单加了一个 21843d9，样式如下。

![screen shot 2018-02-02 at 16 57 50](https://user-images.githubusercontent.com/7903661/35724958-7f44ee08-083a-11e8-8d23-f629be0925b0.png)
![screen shot 2018-02-02 at 16 58 34](https://user-images.githubusercontent.com/7903661/35724963-7f9f0992-083a-11e8-8b6b-c1dc70c5e948.png)

**Comment by cmmei** [comment]
加上了。

**Comment by tsai1993** [comment]
哈哈，真快。
