### ISSUE TITLE
更新几个参数

### ISSUE THREAD

**Issue by tsai1993** [LirenCollege/LirenCollegeBBS#14]
https://github.com/LirenCollege/LirenCollegeBBS/blob/21843d97e5f82eb3d8acba4cd22d08c03170a368/config/config.yaml#L25

建议标题最大长度改为80

https://github.com/LirenCollege/LirenCollegeBBS/blob/21843d97e5f82eb3d8acba4cd22d08c03170a368/config/config.yaml#L27

建议发帖间隔改为300秒

https://github.com/LirenCollege/LirenCollegeBBS/blob/21843d97e5f82eb3d8acba4cd22d08c03170a368/config/config.yaml#L29

建议发帖间隔改为 300秒

小学生真烦😑

**Comment by cmmei** [comment]
已修改更新。

**Comment by cmmei** [comment]
是否需要一个 帖子置顶功能？暂时只是 站务 公告置顶。

**Comment by tsai1993** [comment]
@cmmei 可是好像没有置顶功能啊，我不知道怎么加。你会的话就直接加吧。

**Comment by tsai1993** [comment]
我看了一下 youbbs，好像是直接在index.html里添加的。
