### ISSUE TITLE
只能注册审核制了……

### ISSUE THREAD

**Issue by tsai1993** [LirenCollege/LirenCollegeBBS#16]
https://github.com/LirenCollege/LirenCollegeBBS/blob/482c822b888a76c7c7e84b33b50341d0797b4c17/config/config.yaml#L31

没办法，只能采取注册审核制了，`RegReview` 改为 true

**Comment by cmmei** [comment]
修改了，registertest  试了一下，可以，注册需要审核。

**Comment by cmmei** [comment]
but, 这个怎么审核，啥信息都没有。。。

**Comment by tsai1993** [comment]
可以要求注册用户编辑个人信息，长远来说可能还是需要验证码。

**Comment by tsai1993** [comment]
如果采取了注册审核，发帖间隔可以调整为60秒，回帖间隔调整为30或者20秒。

**Comment by cmmei** [comment]
调整了，60s, 20s

**Comment by cmmei** [comment]
放出的那些，又炸了。

**Comment by tsai1993** [comment]
我也很苦恼……

**Comment by tsai1993** [comment]
不是放出来的，之前就没封完……

**Comment by tsai1993** [comment]
9454e566d245dd1fd34666dbd65a1ddd4839d4f3

在用户管理页添加了info信息

**Comment by cmmei** [comment]
更新了显示 info 信息。

**Comment by tsai1993** [comment]
尝试添加了一个置顶的帖子。感觉不是很好看，尤其是移动端。8e3904dd38ea369fca859b5ad46bdfc5a2c97ec2

![screen shot 2018-03-27 at 22 44 38](https://user-images.githubusercontent.com/7903661/37974947-c08e3a40-3210-11e8-945c-ce5cadd2d330.png)
![screen shot 2018-03-27 at 22 50 49](https://user-images.githubusercontent.com/7903661/37975204-5d0a9fee-3211-11e8-91fb-76b0065438e9.png)

**Comment by tsai1993** [comment]
另外，在注册页面底部加了一行说明。
8d59ba2eccce3fca0a3ed020d7410c2ad35d9ed7

**Comment by tsai1993** [comment]
感觉还是去掉中间的换行好看一点。

**Comment by tsai1993** [comment]
要不还是关闭注册审核吧。好像那帮小学生不怎么来了。

**Comment by cmmei** [comment]
关了注册审核。加了置顶说明。

**Comment by tsai1993** [comment]
辛苦了
