### ISSUE TITLE
移动端置顶修改

### ISSUE THREAD

**Issue by tsai1993** [LirenCollege/LirenCollegeBBS#17]
这个实在不好看，最好只保留一行，比如“不需手机号或邮箱即可注册和发言”

**Comment by tsai1993** [comment]
或者不加也行

**Comment by cmmei** [comment]
got

**Comment by tsai1993** [comment]
你顺便把这个 bug 也修复了吧，https://github.com/ego008/goyoubbs/issues/6，

5eaa706921bb5bede3d046db6cd6d056c4413b1c

**Comment by cmmei** [comment]
ok 了

**Comment by tsai1993** [comment]
Good job!
