### ISSUE TITLE
域名建议

### ISSUE THREAD

**Issue by cmmei** [LirenCollege/LirenCollegeBBS#2]
- lrcbbs.org
- lrcbbs.xyz
- lrcbbs.com

**Comment by tsai1993** [comment]
可以用 lirencollege.xyz/bbs 这种子域名么？

**Comment by cmmei** [comment]
bbs.lirencollege.xyz 应该可以。

**Comment by cmmei** [comment]
我在 lirencollege.xyz  添加了 A 记录，bbs.lirencollege.xyz 指向 123.56.10.32

**Comment by tsai1993** [comment]
先别了，乞丐版阿里云内存耗尽，bbs 开张尚需时日。

应该是指向 123.56.10.32:8000

**Comment by cmmei** [comment]
端口不能设置，要不我在 vultr 增加一个服务器试试？

**Comment by tsai1993** [comment]
端口不能设置，那应该是只能 80 端口，我改了就行。

内存耗尽的问题应该是我数据库的问题。我再看看文档。先不着急。

**Comment by tsai1993** [comment]
我已经改成80端口了，直接映射到 123.56.10.32 就行。内存耗尽的问题我再看看。

**Comment by cmmei** [comment]
ok 了，可以打开了。

**Comment by tsai1993** [comment]
应该是要一段时间等 DNS 部署和解析，应该没问题。
