### ISSUE TITLE
ip 指向域名

### ISSUE THREAD

**Issue by cmmei** [LirenCollege/LirenCollegeBBS#3]
域名那里添加了 A 记录，是不是在这里也需要添加一个 CNAME 记录？ 这么久了指定域名还没生效。

```bbs.lirencollege.xyz```

**Comment by tsai1993** [comment]
ping `bbs.lirencollege.xyz`，得到的仍然是 github 的地址。

https://ransomwaretracker.abuse.ch/ip/192.30.252.154/

**Comment by cmmei** [comment]
如果只是 域名管理 添加了 A 记录，是单向指定，123.56.10.32 并不会识别到。lirencollege.xyz 站点就是设置了 A 记录指向 github ，github 里面也添加了 CNAME 说明。

**Comment by tsai1993** [comment]
但是即使服务器没有任何配置，ping `bbs.lirencollege.xyz`，也应该返回的是绑定的地址。参见 <http://www.paincker.com/website-primer-4> 测试域名解析是否成功

**Comment by cmmei** [comment]
现在 ping ```bbs.lirencollege.xyz``` ，指向 75.126.104.250 ，同时也 ping 不通。

**Comment by tsai1993** [comment]
我再看看

**Comment by cmmei** [comment]
感觉是 阿里云 的问题，我刚才尝试把 ```bbs.lirencollege.xyz``` 指向我在 vultr 的服务器，可以 ping 通。

**Comment by tsai1993** [comment]
你在 vultr 的服务器什么配置？如果可以的话直接迁过去就好了。

**Comment by cmmei** [comment]
ubuntu 服务器，上传这些，安装 go ，应该和你的差不多。

**Comment by tsai1993** [comment]
我知道了，应该是我没有备案。

**Comment by tsai1993** [comment]
服务器内存如果有 1G 的话就行。

不用任何安装，你在 /srv 目录下创建一个新目录 www/，一会儿我把数据打包给你

**Comment by cmmei** [comment]
好的。

**Comment by tsai1993** [comment]
http://123.56.10.32:8000/

你把 bbs.zip 下载之后上传，解压之后，运行 nohup ./goyoubbs 就行

**Comment by tsai1993** [comment]
下载好了说一声。

**Comment by cmmei** [comment]
下载好了。

**Comment by cmmei** [comment]
> 运行 nohup ./goyoubbs 

解压出来 youbbs 文件夹，里面有一些文件。 有 nohup.out  和 goyoubbs

**Comment by tsai1993** [comment]
没关系，加 nohup 是为了防止 ssh 断开之后不运行了。

**Comment by tsai1993** [comment]
成功了，yeah！

**Comment by cmmei** [comment]
运行 ```nohup ./goyoubbs```  ，返回了

```nohup: ignoring input and appending output to 'nohup.out'```

**Comment by tsai1993** [comment]
正常现象。如果要重启进程，你可能需要

`ps - ef | grep you`

找到 goyoubbs，然后

`kill -9 进程号`
