### ISSUE TITLE
显示时间应为 UTC+8 

### ISSUE THREAD

**Issue by tsai1993** [LirenCollege/LirenCollegeBBS#5]

**Comment by cmmei** [comment]
可能和服务器的时间有关。刚才看远程登录后显示时间是1月10日 21点。

**Comment by cmmei** [comment]
date -R  查了下服务器时间，显示 2018年1月11日 06：37  +0000   应该是不在相同时区的原因。

**Comment by cmmei** [comment]
服务器时区改到 东八区了。

**Comment by tsai1993** [comment]
发了一个新帖，没变化啊。是不是需要重启啊。

**Comment by cmmei** [comment]
好了。刚才把 goyoubbs 重启了一下。

**Comment by tsai1993** [comment]
更新主程序之后时间又不对了

**Comment by cmmei** [comment]
配置里改成了 ```TimeZone : 8```   好了。

**Comment by tsai1993** [comment]
ok，辛苦了
