### ISSUE TITLE
建议更改名称

### ISSUE THREAD

**Issue by tsai1993** [LirenCollege/LirenCollegeBBS#6]
LirenCollegeBBS 名称太长了，而且会不会把受众局限在立大圈里？我倾向于改一个名字。

我一直对公共论坛有兴趣，[V2EX](https://www.v2ex.com/) 潜水多年，觉得也是有可能做一个比较好的公共论坛。由于 V2EX 近来限制愈多，所以一怒之下另造轮子。
![screen shot 2018-01-11 at 14 20 02](https://user-images.githubusercontent.com/7903661/34812504-cf9f6a24-f6e0-11e7-9c65-a3ae519fc804.png)

除了改名之外，问下服务器是在国外么？域名呢？

**Comment by cmmei** [comment]
要改名字的话，域名也需要换别的。

服务器是在国外，域名也在国外，在 name.com 注册的。

**Comment by tsai1993** [comment]
不用啊，域名啥的不用换。域名无所谓，还是挂在 lirencollege.xyz 下面。
 
改名字直接把 `config/config.yaml` 里面的 `Name` 改了就行。

**Comment by tsai1993** [comment]
服务器和域名都在国外就不用担心了，我希望做一个不需要用户手机号的论坛。

**Comment by cmmei** [comment]
第三方快捷登录 也可以不要。

名字 还没想到改啥好。

**Comment by cmmei** [comment]
期望这个论坛的作用会是什么？

分享、讨论。

**Comment by tsai1993** [comment]
一个自由讨论的地方吧。其实用户是啥样，论坛就是啥样。

还是觉得像 V2EX 那样，有分享发现，有分享创造，不讨论分享盗版。最主要的还是一个公共交流的平台吧，微信这种实在没有意思。其实主要是觉得国内现在没有一个真正可以自由讨论的地方， 敏感词已经多到发指，比如听说很多人用户名里包含xi就被封禁，而且现在都必须实名，绑定手机号。我是实在不喜欢这些限制。

**Comment by cmmei** [comment]
FreeBBS  如何？ = . =

**Comment by tsai1993** [comment]
第一眼看成了 FreeBSD，囧。直接 free 感觉怪怪的，有个论坛叫1984bbs，我有点想叫 2049bbs。毕竟最近 blade runner 挺火的。

**Comment by cmmei** [comment]
那就先用 2049bbs 吧，想不出其它合适的。

**Comment by tsai1993** [comment]
好吧，那就先 2049BBS 吧。

**Comment by cmmei** [comment]
名字 OK 了。

发现一个小问题，在微信里打开注册时，始终跳到 登录 页面，而不是 注册 页面。

**Comment by tsai1993** [comment]
确实有这个奇怪的问题，不过我猜大概率是微信的问题。
